# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parallel_sorting.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='parallel_sorting.proto',
  package='parallelsorting',
  syntax='proto3',
  serialized_options=_b('\n io.grpc.examples.parallelsortingB\017ParallelSortingP\001\242\002\002PS'),
  serialized_pb=_b('\n\x16parallel_sorting.proto\x12\x0fparallelsorting\"\x1d\n\x05Tuple\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x05\n\x03NIL\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04item\x18\x01 \x01(\x05\"\x17\n\x07\x41\x64\x64ress\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t2\xf6\x07\n\x0fParallelSorting\x12<\n\x07\x63ompare\x12\x16.parallelsorting.Tuple\x1a\x17.parallelsorting.Result\"\x00\x12:\n\x07get_min\x12\x14.parallelsorting.NIL\x1a\x17.parallelsorting.Result\"\x00\x12:\n\x07get_max\x12\x14.parallelsorting.NIL\x1a\x17.parallelsorting.Result\"\x00\x12\x39\n\x04swap\x12\x16.parallelsorting.Tuple\x1a\x17.parallelsorting.Result\"\x00\x12>\n\x0bremote_sort\x12\x14.parallelsorting.NIL\x1a\x15.parallelsorting.Data\"\x00\x30\x01\x12@\n\rcheck_if_busy\x12\x14.parallelsorting.NIL\x1a\x17.parallelsorting.Status\"\x00\x12\x42\n\x0cprocess_data\x12\x15.parallelsorting.Data\x1a\x15.parallelsorting.Data\"\x00(\x01\x30\x01\x12\x43\n\x10start_connection\x12\x14.parallelsorting.NIL\x1a\x17.parallelsorting.Status\"\x00\x12\x41\n\x0e\x65nd_connection\x12\x14.parallelsorting.NIL\x1a\x17.parallelsorting.Status\"\x00\x12J\n\x17get_partial_sorted_data\x12\x14.parallelsorting.NIL\x1a\x15.parallelsorting.Data\"\x00\x30\x01\x12\x41\n\nconnect_to\x12\x18.parallelsorting.Address\x1a\x17.parallelsorting.Status\"\x00\x12G\n\x14\x66orward_data_to_peer\x12\x15.parallelsorting.Data\x1a\x14.parallelsorting.NIL\"\x00(\x01\x12=\n\ninput_data\x12\x15.parallelsorting.Data\x1a\x14.parallelsorting.NIL\"\x00(\x01\x12I\n\x16\x66\x65tch_result_from_peer\x12\x14.parallelsorting.NIL\x1a\x15.parallelsorting.Data\"\x00\x30\x01\x12\x42\n\x10remove_duplicate\x12\x16.parallelsorting.Tuple\x1a\x14.parallelsorting.NIL\"\x00\x42:\n io.grpc.examples.parallelsortingB\x0fParallelSortingP\x01\xa2\x02\x02PSb\x06proto3')
)




_TUPLE = _descriptor.Descriptor(
  name='Tuple',
  full_name='parallelsorting.Tuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='parallelsorting.Tuple.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='parallelsorting.Tuple.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=72,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='parallelsorting.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='parallelsorting.Result.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=98,
)


_NIL = _descriptor.Descriptor(
  name='NIL',
  full_name='parallelsorting.NIL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=105,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='parallelsorting.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='parallelsorting.Status.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=131,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='parallelsorting.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='parallelsorting.Data.item', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=153,
)


_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='parallelsorting.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='parallelsorting.Address.addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['Tuple'] = _TUPLE
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['NIL'] = _NIL
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tuple = _reflection.GeneratedProtocolMessageType('Tuple', (_message.Message,), dict(
  DESCRIPTOR = _TUPLE,
  __module__ = 'parallel_sorting_pb2'
  # @@protoc_insertion_point(class_scope:parallelsorting.Tuple)
  ))
_sym_db.RegisterMessage(Tuple)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'parallel_sorting_pb2'
  # @@protoc_insertion_point(class_scope:parallelsorting.Result)
  ))
_sym_db.RegisterMessage(Result)

NIL = _reflection.GeneratedProtocolMessageType('NIL', (_message.Message,), dict(
  DESCRIPTOR = _NIL,
  __module__ = 'parallel_sorting_pb2'
  # @@protoc_insertion_point(class_scope:parallelsorting.NIL)
  ))
_sym_db.RegisterMessage(NIL)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'parallel_sorting_pb2'
  # @@protoc_insertion_point(class_scope:parallelsorting.Status)
  ))
_sym_db.RegisterMessage(Status)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'parallel_sorting_pb2'
  # @@protoc_insertion_point(class_scope:parallelsorting.Data)
  ))
_sym_db.RegisterMessage(Data)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESS,
  __module__ = 'parallel_sorting_pb2'
  # @@protoc_insertion_point(class_scope:parallelsorting.Address)
  ))
_sym_db.RegisterMessage(Address)


DESCRIPTOR._options = None

_PARALLELSORTING = _descriptor.ServiceDescriptor(
  name='ParallelSorting',
  full_name='parallelsorting.ParallelSorting',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=181,
  serialized_end=1195,
  methods=[
  _descriptor.MethodDescriptor(
    name='compare',
    full_name='parallelsorting.ParallelSorting.compare',
    index=0,
    containing_service=None,
    input_type=_TUPLE,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_min',
    full_name='parallelsorting.ParallelSorting.get_min',
    index=1,
    containing_service=None,
    input_type=_NIL,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_max',
    full_name='parallelsorting.ParallelSorting.get_max',
    index=2,
    containing_service=None,
    input_type=_NIL,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='swap',
    full_name='parallelsorting.ParallelSorting.swap',
    index=3,
    containing_service=None,
    input_type=_TUPLE,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='remote_sort',
    full_name='parallelsorting.ParallelSorting.remote_sort',
    index=4,
    containing_service=None,
    input_type=_NIL,
    output_type=_DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='check_if_busy',
    full_name='parallelsorting.ParallelSorting.check_if_busy',
    index=5,
    containing_service=None,
    input_type=_NIL,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='process_data',
    full_name='parallelsorting.ParallelSorting.process_data',
    index=6,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='start_connection',
    full_name='parallelsorting.ParallelSorting.start_connection',
    index=7,
    containing_service=None,
    input_type=_NIL,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='end_connection',
    full_name='parallelsorting.ParallelSorting.end_connection',
    index=8,
    containing_service=None,
    input_type=_NIL,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_partial_sorted_data',
    full_name='parallelsorting.ParallelSorting.get_partial_sorted_data',
    index=9,
    containing_service=None,
    input_type=_NIL,
    output_type=_DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='connect_to',
    full_name='parallelsorting.ParallelSorting.connect_to',
    index=10,
    containing_service=None,
    input_type=_ADDRESS,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='forward_data_to_peer',
    full_name='parallelsorting.ParallelSorting.forward_data_to_peer',
    index=11,
    containing_service=None,
    input_type=_DATA,
    output_type=_NIL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='input_data',
    full_name='parallelsorting.ParallelSorting.input_data',
    index=12,
    containing_service=None,
    input_type=_DATA,
    output_type=_NIL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='fetch_result_from_peer',
    full_name='parallelsorting.ParallelSorting.fetch_result_from_peer',
    index=13,
    containing_service=None,
    input_type=_NIL,
    output_type=_DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='remove_duplicate',
    full_name='parallelsorting.ParallelSorting.remove_duplicate',
    index=14,
    containing_service=None,
    input_type=_TUPLE,
    output_type=_NIL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARALLELSORTING)

DESCRIPTOR.services_by_name['ParallelSorting'] = _PARALLELSORTING

# @@protoc_insertion_point(module_scope)
