# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import route_guide_pb2 as route__guide__pb2


class RouteGuideStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFeature = channel.unary_unary(
        '/routeguide.RouteGuide/GetFeature',
        request_serializer=route__guide__pb2.Point.SerializeToString,
        response_deserializer=route__guide__pb2.Feature.FromString,
        )
    self.ListFeatures = channel.unary_stream(
        '/routeguide.RouteGuide/ListFeatures',
        request_serializer=route__guide__pb2.Rectangle.SerializeToString,
        response_deserializer=route__guide__pb2.Feature.FromString,
        )
    self.RecordRoute = channel.stream_unary(
        '/routeguide.RouteGuide/RecordRoute',
        request_serializer=route__guide__pb2.Point.SerializeToString,
        response_deserializer=route__guide__pb2.RouteSummary.FromString,
        )
    self.RouteChat = channel.stream_stream(
        '/routeguide.RouteGuide/RouteChat',
        request_serializer=route__guide__pb2.RouteNote.SerializeToString,
        response_deserializer=route__guide__pb2.RouteNote.FromString,
        )
    self.compare = channel.unary_unary(
        '/routeguide.RouteGuide/compare',
        request_serializer=route__guide__pb2.Tuple.SerializeToString,
        response_deserializer=route__guide__pb2.Result.FromString,
        )
    self.get_min = channel.unary_unary(
        '/routeguide.RouteGuide/get_min',
        request_serializer=route__guide__pb2.NIL.SerializeToString,
        response_deserializer=route__guide__pb2.Result.FromString,
        )
    self.get_max = channel.unary_unary(
        '/routeguide.RouteGuide/get_max',
        request_serializer=route__guide__pb2.NIL.SerializeToString,
        response_deserializer=route__guide__pb2.Result.FromString,
        )
    self.swap = channel.unary_unary(
        '/routeguide.RouteGuide/swap',
        request_serializer=route__guide__pb2.Tuple.SerializeToString,
        response_deserializer=route__guide__pb2.Result.FromString,
        )
    self.remote_sort = channel.unary_stream(
        '/routeguide.RouteGuide/remote_sort',
        request_serializer=route__guide__pb2.NIL.SerializeToString,
        response_deserializer=route__guide__pb2.Data.FromString,
        )
    self.check_if_busy = channel.unary_unary(
        '/routeguide.RouteGuide/check_if_busy',
        request_serializer=route__guide__pb2.NIL.SerializeToString,
        response_deserializer=route__guide__pb2.Status.FromString,
        )
    self.process_data = channel.stream_stream(
        '/routeguide.RouteGuide/process_data',
        request_serializer=route__guide__pb2.Data.SerializeToString,
        response_deserializer=route__guide__pb2.Data.FromString,
        )
    self.start_connection = channel.unary_unary(
        '/routeguide.RouteGuide/start_connection',
        request_serializer=route__guide__pb2.NIL.SerializeToString,
        response_deserializer=route__guide__pb2.Status.FromString,
        )
    self.end_connection = channel.unary_unary(
        '/routeguide.RouteGuide/end_connection',
        request_serializer=route__guide__pb2.NIL.SerializeToString,
        response_deserializer=route__guide__pb2.Status.FromString,
        )
    self.get_partial_sorted_data = channel.unary_stream(
        '/routeguide.RouteGuide/get_partial_sorted_data',
        request_serializer=route__guide__pb2.NIL.SerializeToString,
        response_deserializer=route__guide__pb2.Data.FromString,
        )
    self.connect_to = channel.unary_unary(
        '/routeguide.RouteGuide/connect_to',
        request_serializer=route__guide__pb2.Address.SerializeToString,
        response_deserializer=route__guide__pb2.Status.FromString,
        )
    self.forward_data_to_peer = channel.stream_unary(
        '/routeguide.RouteGuide/forward_data_to_peer',
        request_serializer=route__guide__pb2.Data.SerializeToString,
        response_deserializer=route__guide__pb2.NIL.FromString,
        )
    self.input_data = channel.stream_unary(
        '/routeguide.RouteGuide/input_data',
        request_serializer=route__guide__pb2.Data.SerializeToString,
        response_deserializer=route__guide__pb2.NIL.FromString,
        )
    self.fetch_result_from_peer = channel.unary_stream(
        '/routeguide.RouteGuide/fetch_result_from_peer',
        request_serializer=route__guide__pb2.NIL.SerializeToString,
        response_deserializer=route__guide__pb2.Data.FromString,
        )


class RouteGuideServicer(object):
  """Interface exported by the server.
  """

  def GetFeature(self, request, context):
    """A simple RPC.

    Obtains the feature at a given position.

    A feature with an empty name is returned if there's no feature at the given
    position.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListFeatures(self, request, context):
    """A server-to-client streaming RPC.

    Obtains the Features available within the given Rectangle.  Results are
    streamed rather than returned at once (e.g. in a response message with a
    repeated field), as the rectangle may cover a large area and contain a
    huge number of features.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RecordRoute(self, request_iterator, context):
    """A client-to-server streaming RPC.

    Accepts a stream of Points on a route being traversed, returning a
    RouteSummary when traversal is completed.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RouteChat(self, request_iterator, context):
    """A Bidirectional streaming RPC.

    Accepts a stream of RouteNotes sent while a route is being traversed,
    while receiving other RouteNotes (e.g. from other users).
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def compare(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_min(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_max(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def swap(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def remote_sort(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def check_if_busy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def process_data(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def start_connection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def end_connection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_partial_sorted_data(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def connect_to(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def forward_data_to_peer(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def input_data(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def fetch_result_from_peer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFeature': grpc.unary_unary_rpc_method_handler(
          servicer.GetFeature,
          request_deserializer=route__guide__pb2.Point.FromString,
          response_serializer=route__guide__pb2.Feature.SerializeToString,
      ),
      'ListFeatures': grpc.unary_stream_rpc_method_handler(
          servicer.ListFeatures,
          request_deserializer=route__guide__pb2.Rectangle.FromString,
          response_serializer=route__guide__pb2.Feature.SerializeToString,
      ),
      'RecordRoute': grpc.stream_unary_rpc_method_handler(
          servicer.RecordRoute,
          request_deserializer=route__guide__pb2.Point.FromString,
          response_serializer=route__guide__pb2.RouteSummary.SerializeToString,
      ),
      'RouteChat': grpc.stream_stream_rpc_method_handler(
          servicer.RouteChat,
          request_deserializer=route__guide__pb2.RouteNote.FromString,
          response_serializer=route__guide__pb2.RouteNote.SerializeToString,
      ),
      'compare': grpc.unary_unary_rpc_method_handler(
          servicer.compare,
          request_deserializer=route__guide__pb2.Tuple.FromString,
          response_serializer=route__guide__pb2.Result.SerializeToString,
      ),
      'get_min': grpc.unary_unary_rpc_method_handler(
          servicer.get_min,
          request_deserializer=route__guide__pb2.NIL.FromString,
          response_serializer=route__guide__pb2.Result.SerializeToString,
      ),
      'get_max': grpc.unary_unary_rpc_method_handler(
          servicer.get_max,
          request_deserializer=route__guide__pb2.NIL.FromString,
          response_serializer=route__guide__pb2.Result.SerializeToString,
      ),
      'swap': grpc.unary_unary_rpc_method_handler(
          servicer.swap,
          request_deserializer=route__guide__pb2.Tuple.FromString,
          response_serializer=route__guide__pb2.Result.SerializeToString,
      ),
      'remote_sort': grpc.unary_stream_rpc_method_handler(
          servicer.remote_sort,
          request_deserializer=route__guide__pb2.NIL.FromString,
          response_serializer=route__guide__pb2.Data.SerializeToString,
      ),
      'check_if_busy': grpc.unary_unary_rpc_method_handler(
          servicer.check_if_busy,
          request_deserializer=route__guide__pb2.NIL.FromString,
          response_serializer=route__guide__pb2.Status.SerializeToString,
      ),
      'process_data': grpc.stream_stream_rpc_method_handler(
          servicer.process_data,
          request_deserializer=route__guide__pb2.Data.FromString,
          response_serializer=route__guide__pb2.Data.SerializeToString,
      ),
      'start_connection': grpc.unary_unary_rpc_method_handler(
          servicer.start_connection,
          request_deserializer=route__guide__pb2.NIL.FromString,
          response_serializer=route__guide__pb2.Status.SerializeToString,
      ),
      'end_connection': grpc.unary_unary_rpc_method_handler(
          servicer.end_connection,
          request_deserializer=route__guide__pb2.NIL.FromString,
          response_serializer=route__guide__pb2.Status.SerializeToString,
      ),
      'get_partial_sorted_data': grpc.unary_stream_rpc_method_handler(
          servicer.get_partial_sorted_data,
          request_deserializer=route__guide__pb2.NIL.FromString,
          response_serializer=route__guide__pb2.Data.SerializeToString,
      ),
      'connect_to': grpc.unary_unary_rpc_method_handler(
          servicer.connect_to,
          request_deserializer=route__guide__pb2.Address.FromString,
          response_serializer=route__guide__pb2.Status.SerializeToString,
      ),
      'forward_data_to_peer': grpc.stream_unary_rpc_method_handler(
          servicer.forward_data_to_peer,
          request_deserializer=route__guide__pb2.Data.FromString,
          response_serializer=route__guide__pb2.NIL.SerializeToString,
      ),
      'input_data': grpc.stream_unary_rpc_method_handler(
          servicer.input_data,
          request_deserializer=route__guide__pb2.Data.FromString,
          response_serializer=route__guide__pb2.NIL.SerializeToString,
      ),
      'fetch_result_from_peer': grpc.unary_stream_rpc_method_handler(
          servicer.fetch_result_from_peer,
          request_deserializer=route__guide__pb2.NIL.FromString,
          response_serializer=route__guide__pb2.Data.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'routeguide.RouteGuide', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
